---
# Project information
site_name: Linux Guide and Hints
site_url: https://linuxguideandhints.com
site_description: >-
  Linux Guide and Hints Documentation

# Repository
repo_url: https://github.com/nazunalika/linux-guide-and-hints
repo_name: nazunalika/linux-guide-and-hints
edit_uri: edit/master/docs/

# Copyright
copyright: Copyright 2025, remyabel, nazunalika

# Configuration
theme:
  variant: classic
  highlightjs: true
  nav_style: dark
  hljs_languages:
    - bash
    - perl
    - python
    - yaml
    - ini
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.integrate
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  custom_dir: overrides

# Plugins
plugins:
  - autolinks
  - awesome-nav
  - git-revision-date-localized
  - search
#  - macros:
#      include_dir: docs/include

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.emoji:
      emoji_index: !!python/name:material.emoji.twemoji
      emoji_generator: !!python/name:material.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
